Repository Shining-Jicheon-Stars/yjg-laravel-backend, pull requests merged in 2024-04, with the labels that each got.

#446 Feat: Scheduled Jobを実装
  app/Console/Kernel.php
  app/Http/Kernel.php
Labels: ✨ Feat, ♻️ Refactor

#448 Fix: 管理者検索エラーを解決
  app/Http/Controllers/Auth/AdminController.php
Labels: 🐛 Fix

#449 Refactor: scheduled jobを修正
  app/Console/Kernel.php
Labels: ♻️ Refactor

#450 Fix: 美容室の権限エラーを解決
  app/Http/Controllers/MeetingRoom/MeetingRoomController.php
  app/Policies/SalonPolicy.php
Labels: ♻️ Refactor, 🐛 Fix

#451 fix:restaurant_menu, apply API 修正
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
  app/Http/Controllers/Restaurant/RestaurantMenusController.php
  app/Imports/RestaurantMenuImport.php
  storage/api-docs/api-docs.json
Labels: 🐛 Fix

#452 Fix: ユーザー情報修正エラーを解決
  routes/api.php
Labels: 🐛 Fix

#455 Fix: noticeの連関関係エラーを解決
  app/Http/Controllers/Administrator/NoticeController.php
Labels: 🐛 Fix

#458 Fix: noticeの検索エラーを解決
  app/Http/Controllers/Administrator/NoticeController.php
Labels: 🐛 Fix

#460 Fix: ユーザーと管理者のエラーを解決
  app/Http/Controllers/Auth/AdminController.php
  app/Http/Controllers/Auth/UserController.php
Labels: 🐛 Fix

#461 Fix: notice作成エラーを解決
  app/Models/Notice.php
Labels: 🐛 Fix

#462 Fix: adminList関数のresponseを修正
  app/Http/Controllers/Auth/AdminController.php
Labels: 🐛 Fix

#463 feat:restaurant_apply_division Web API 追加
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
  routes/api.php
Labels: ✨ Feat

#464 Refactor: ユーザー情報修正機能を改善
  app/Http/Controllers/Auth/UserController.php
  routes/api.php
Labels: ♻️ Refactor

#465 Refactor: routeを変更
  app/Http/Controllers/Auth/AdminController.php
  app/Http/Controllers/Auth/PasswordResetCodeController.php
  app/Http/Controllers/Auth/UserController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ♻️ Refactor

#467 Refactor: routeを整理
  app/Http/Controllers/Auth/AdminController.php
  app/Http/Controllers/Auth/UserController.php
  routes/api.php
Labels: ♻️ Refactor

#468 Refactor: routeを整理
  routes/api.php
Labels: ♻️ Refactor

#469 Migration: eventを作成
  app/Console/Kernel.php
  codepipeline.md
  database/migrations/2024_04_04_093155_create_clean_up_reset_code_event.php
Labels: 🔥 Remove, ♻️ Refactor

#471 Fix: routeエラーを解決
  routes/api.php
Labels: 🐛 Fix

#473 fix:restaurant migration 修正
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
  database/migrations/2024_02_21_212448_create_semester_meal_types_table.php
  database/migrations/2024_02_21_212458_create_weekend_meal_types_table.php
  database/migrations/2024_03_04_111500_create_bus_rounds_table.php
  database/migrations/2024_03_04_111524_create_bus_schedules_table.php
  database/migrations/2024_03_07_203208_create_restaurant_menu_dates_table.php
  database/migrations/2024_03_11_193806_create_restaurant_menus_table.php
  database/migrations/2024_03_25_193642_create_restaurant_accounts_table.php
  routes/api.php
Labels: 🐛 Fix

#474 Chore: 認証関連設定を修正
  app/Http/Kernel.php
  config/session.php
Labels: 🔨 Chore

#475 Feat: release用のactionを実装
  .github/workflows/add_pull_request_assignee.yml
  .github/workflows/create_release.yml
  .github/workflows/deployment.yml
  .github/workflows/integration.yml
  .github/workflows/issue_assignee.yml
Labels: ✨ Feat, 🔥 Remove, ♻️ Refactor

#476 Refactor: release用のactionを修正
  .github/workflows/create_release.yml
Labels: ♻️ Refactor

#477 Fix: deployment用のactionを修正
  .github/workflows/create_release.yml
  .github/workflows/deployment.yml
Labels: ♻️ Refactor, 🐛 Fix

#478 Fix: release用actionを修正
  .github/workflows/create_release.yml
  release-note.md
Labels: 🐛 Fix

#479 Fix: デプロイエラーを解決
  .github/workflows/add_pull_request_assignee.yml
  .github/workflows/create_release.yml
  .github/workflows/deployment.yml
Labels: ♻️ Refactor, 🐛 Fix

#480 Refactor: GITHUB_TOKENを利用
  .github/workflows/create_release.yml
Labels: ♻️ Refactor

#481 Fix: クエリエラーを解決
  app/Http/Controllers/Administrator/AbsenceController.php
  app/Http/Controllers/Administrator/NoticeController.php
Labels: ♻️ Refactor, 🐛 Fix

#482 Refactor: ログインにformRequestを適用
  app/Http/Controllers/Auth/AdminController.php
  app/Http/Controllers/Auth/UserController.php
  app/Http/Controllers/Controller.php
  app/Http/Requests/LoginRequest.php
Labels: ♻️ Refactor

#483 Refactor: メール形式を修正、トークンの時間修正
  config/jwt.php
  resources/views/mail/password.blade.php
Labels: ♻️ Refactor, 🔨 Chore

#484 fix:restaurant_meal_type and apply API 修正
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
  app/Http/Controllers/Restaurant/RestaurantMenusController.php
  app/Http/Controllers/Restaurant/SemesterMealTypeController.php
  app/Http/Controllers/Restaurant/WeekendMealTypeController.php
  routes/api.php
Labels: 🐛 Fix

#485 remove:restaurant_apply_division API and swagger 修正
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
  app/Http/Controllers/Restaurant/RestaurantSemesterController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  storage/api-docs/api-docs.json
Labels: 🔥 Remove

#486 Fix: refreshエラーを解決
  app/Http/Middleware/Authenticate.php
Labels: 🐛 Fix

#487 fix:restaurant_apply_division API 修正
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
Labels: 🐛 Fix

#488 Test: デプロイテスト
  app/Http/Controllers/Administrator/AbsenceController.php
  app/Http/Controllers/Administrator/NoticeController.php
  app/Http/Controllers/Auth/AdminController.php
  app/Http/Controllers/Auth/UserController.php
  app/Http/Controllers/Controller.php
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
  app/Http/Controllers/Restaurant/RestaurantMenusController.php
  app/Http/Controllers/Restaurant/RestaurantSemesterController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  app/Http/Controllers/Restaurant/SemesterMealTypeController.php
  app/Http/Controllers/Restaurant/WeekendMealTypeController.php
  app/Http/Kernel.php
  app/Http/Middleware/Authenticate.php
  app/Http/Requests/LoginRequest.php
  config/jwt.php
  config/session.php
  database/migrations/2024_02_21_212448_create_semester_meal_types_table.php
  database/migrations/2024_02_21_212458_create_weekend_meal_types_table.php
  database/migrations/2024_03_04_111500_create_bus_rounds_table.php
  database/migrations/2024_03_04_111524_create_bus_schedules_table.php
  database/migrations/2024_03_07_203208_create_restaurant_menu_dates_table.php
  database/migrations/2024_03_11_193806_create_restaurant_menus_table.php
  database/migrations/2024_03_25_193642_create_restaurant_accounts_table.php
  resources/views/mail/password.blade.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🧪 Test

#489 Fix: 認証middlewareを修正
  app/Http/Middleware/Authenticate.php
Labels: 🐛 Fix

#490 Test: デプロイテスト
  app/Http/Middleware/Authenticate.php
Labels: 🧪 Test

#491 Refactor: パスワードの検証機能を改善
  app/Http/Controllers/Auth/UserController.php
Labels: ♻️ Refactor

#492 fix:restaurant_apply_division API weekendCheck,semesterCheck修正
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
Labels: 🐛 Fix

#494 fix:restaurant_apply_division weekendCheck API 修正
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
Labels: 🐛 Fix

#495 Deploy: v0.0.1
  app/Http/Controllers/Auth/UserController.php
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 📦 Deploy

#496 Refactor: ユーザー検証middlewareを修正
  app/Http/Kernel.php
  app/Http/Middleware/Authenticate.php
  app/Http/Middleware/AuthenticateRefresh.php
  app/Http/Middleware/TokenType.php
  routes/api.php
Labels: ✨ Feat, 🔥 Remove, ♻️ Refactor

#497 Deploy: v0.0.2
  app/Http/Kernel.php
  app/Http/Middleware/Authenticate.php
  app/Http/Middleware/AuthenticateRefresh.php
  app/Http/Middleware/TokenType.php
  routes/api.php
Labels: 📦 Deploy

#498 fix:restaurant payment API 修正
  app/Http/Controllers/Restaurant/RestaurantSemesterController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  app/Models/RestaurantWeekend.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🐛 Fix

#499 Fix: 管理者の情報修正エラーを解決
  app/Http/Controllers/Auth/AdminController.php
Labels: 🐛 Fix

#500 Fix: アプリのリフレッシュエラーを解決
  app/Http/Middleware/AuthenticateRefresh.php
Labels: 🐛 Fix

#503 Refactor: リターンタイプの整理
  app/Http/Controllers/Administrator/AbsenceController.php
  app/Http/Controllers/Administrator/NoticeController.php
  app/Http/Controllers/AfterService/AfterServiceCommentController.php
  app/Http/Controllers/AfterService/AfterServiceController.php
  app/Http/Controllers/Auth/AdminController.php
  app/Http/Controllers/Auth/PasswordResetCodeController.php
  app/Http/Controllers/Auth/PrivilegeController.php
  app/Http/Controllers/Auth/RefreshController.php
  app/Http/Controllers/Auth/UserController.php
  app/Http/Controllers/MeetingRoom/MeetingRoomController.php
  app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php
  app/Http/Controllers/Restaurant/RestaurantMenusController.php
  app/Http/Controllers/Salon/SalonBreakTimeController.php
  app/Http/Controllers/Salon/SalonBusinessHourController.php
  app/Http/Controllers/Salon/SalonCategoryController.php
  app/Http/Controllers/Salon/SalonReservationController.php
  app/Http/Controllers/Salon/SalonServiceController.php
Labels: ♻️ Refactor

#505 Refactor: validationルールを修正
  app/Http/Controllers/Auth/UserController.php
  lang/kr/validation.php
Labels: ♻️ Refactor

#507 Release/1.0.1
  app/Http/Controllers/Auth/UserController.php
  app/Http/Controllers/Restaurant/RestaurantMenusController.php
  app/Imports/RestaurantMenuImport.php
  lang/kr/validation.php
Labels: 📦 Release

#508 Fix: イメージエラー解決
  Dockerfile
  app/Http/Controllers/AfterService/AfterServiceController.php
Labels: 🐛 Fix

#509 Release/1.0.2
  Dockerfile
  app/Http/Controllers/AfterService/AfterServiceController.php
Labels: 📦 Release

#511 Release/1.0.3
  Dockerfile
  nginx/default.conf
  routes/api.php
Labels: 📦 Release

#512 Fix: イメージエラー解決
  Dockerfile
Labels: 🐛 Fix

#513 Release/1.0.4
  Dockerfile
Labels: 📦 Release

#514 Refactor: トークンの有効時間変更
  config/jwt.php
Labels: ♻️ Refactor

#515 fix:restaurant_apply_division API修正
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
Labels: 🐛 Fix

#516 feat:restaurant_menu upload middleware Cors具現
  app/Http/Controllers/Restaurant/RestaurantMenusController.php
  app/Http/Kernel.php
  app/Http/Middleware/Cors.php
Labels: ✨ Feat
