Repository Shining-Jicheon-Stars/yjg-laravel-backend, pull requests merged in 2024-05, with the labels that each got.

#517 Remove: seederを削除
  database/factories/AdminFactory.php
  database/factories/AfterServiceFactory.php
  database/factories/MeetingRoomReservationFactory.php
  database/factories/NoticeFactory.php
  database/seeders/AbsenceListSeeder.php
  database/seeders/AfterServiceSeeder.php
  database/seeders/DatabaseSeeder.php
  database/seeders/MeetingRoomReservationSeeder.php
  database/seeders/SalonReservationSeeder.php
Labels: 🔥 Remove

#518 Chore: パッケージのアップデート
  composer.json
  composer.lock
Labels: 🔨 Chore

#521 Chore: laravel-firebaseを追加
  app/Models/User.php
  composer.json
  composer.lock
  config/firebase.php
  database/migrations/2014_10_12_000000_create_users_table.php
Labels: 🔨 Chore

#524 Migration: バステーブルを修正
  config/app.php
  database/migrations/2024_03_04_111500_create_bus_rounds_table.php
Labels: 🔨 Chore

#531 Feat: プッシュ通知を実装
  app/Http/Controllers/Administrator/AbsenceController.php
  app/Http/Controllers/Administrator/NoticeController.php
  app/Http/Controllers/AfterService/AfterServiceCommentController.php
  app/Http/Controllers/AfterService/AfterServiceController.php
  app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php
  app/Http/Controllers/Salon/SalonReservationController.php
  app/Services/NotificationService.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2024_03_28_191819_add_admin_column_on_users_table.php
Labels: ✨ Feat

#533 Fix: ログインエラーを解決
  app/Http/Controllers/Auth/UserController.php
Labels: 🐛 Fix

#534 Refactor: プッシュ通知機能を改善
  app/Http/Controllers/Administrator/AbsenceController.php
  app/Http/Controllers/Administrator/NoticeController.php
  app/Http/Controllers/AfterService/AfterServiceCommentController.php
  app/Http/Controllers/AfterService/AfterServiceController.php
  app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php
  app/Http/Controllers/Salon/SalonReservationController.php
  app/Services/NotificationService.php
Labels: ♻️ Refactor

#535 Refactor: パスワードリセット機能のHTTPメソッドを変更
  routes/api.php
Labels: ♻️ Refactor

#536 Feat: email認証middlewareを実装
  app/Http/Kernel.php
  app/Http/Middleware/Authenticate.php
  app/Http/Middleware/AuthenticateEmail.php
  routes/api.php
Labels: ✨ Feat, 🐛 Fix

#537 Remove: CORSミドルウェアを削除
  app/Http/Kernel.php
  app/Http/Middleware/Cors.php
Labels: 🔥 Remove

#539 Feat: プッシュ通知の可否を設定する機能を実装
  app/Http/Controllers/Auth/UserController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, 📝 Docs

#540 Fix: 美容室のプッシュ通知エラーを解決
  app/Http/Controllers/Salon/SalonReservationController.php
Labels: 🐛 Fix

#541 Feat: 週末、学期食事申請のプッシュ通知を実装
  Dockerfile
  app/Console/Kernel.php
  app/Services/NotificationService.php
  app/Tasks/RestaurantSemesterNotification.php
  app/Tasks/RestaurantWeekendNotification.php
  crontab
  routes/api.php
Labels: ✨ Feat, 🔥 Remove, ♻️ Refactor, 🔨 Chore

#542 Chore: Dockerfileを修正
  Dockerfile
Labels: 🔨 Chore

#544 Chore: ワークフローを修正
  .github/workflows/cron_integration.yml
Labels: 🔨 Chore

#545 Chore: ワークフローを修正
  .github/workflows/deployment.yml
Labels: 🔨 Chore

#546 Remove: ワークフローを削除
  .github/workflows/ec2_deployment.yml
Labels: 🔥 Remove

#547 Chore: schedule用のDockerfileを修正
  Dockerfile-cron
Labels: 🔨 Chore

#548 Chore: ワークフローを修正
  .github/workflows/docker_integration.yml
  .github/workflows/laravel_integration.yml
  crontab
Labels: 🔥 Remove, 🔨 Chore

#550 Chore: ワークフローを修正
  .github/workflows/docker_integration.yml
Labels: 🔨 Chore

#551 Chore: ワークフローを修正
  .github/workflows/docker_integration.yml
Labels: 🔨 Chore

#552 Chore: firebaseの設定を変更
  config/firebase.php
Labels: 🔨 Chore

#554 Chore: firebaseの設定を変更
  config/firebase.php
Labels: 🔨 Chore

#555 fix:restaurant_menu API getWeekMenu 修正
  app/Http/Controllers/QRController.php
  app/Http/Controllers/Restaurant/RestaurantMenusController.php
  app/Http/Kernel.php
  app/Imports/RestaurantMenuImport.php
  public/256
  routes/api.php
Labels: 🐛 Fix

#556 fix:restaurant_menu api getWeekMenu 修正
  app/Http/Controllers/Restaurant/RestaurantMenusController.php
Labels: 🐛 Fix

#557 fix:getWeekMenu API 修正
  app/Http/Controllers/QRController.php
  app/Http/Controllers/Restaurant/RestaurantMenusController.php
Labels: 🐛 Fix

#558 feat:QRController API作成
  app/Http/Controllers/QRController.php
  app/Http/Controllers/Restaurant/RestaurantMenusController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, 🐛 Fix

#559 Chore: ポートを変更
  Dockerfile.nginx
  appspec.yml
  nginx/default.conf
Labels: 🔨 Chore

#561 Chore: taskdef.jsonを修正
  taskdef.json
Labels: 🔨 Chore

#562 Release: 1.1.2
  taskdef.json
Labels: 📦 Release
