Repository Shining-Jicheon-Stars/yjg-laravel-backend, pull requests merged in 2024-03, with the labels that each got.

#235 feat: bus_round get API 作成
  app/Http/Controllers/BusScheduleController.php
  app/Http/Controllers/RestaurantSemesterController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat

#238 Fix: admin認証関連エアーを修正
  app/Http/Controllers/Admin/AdminController.php
  app/Http/Kernel.php
  app/Http/Middleware/AdminApprovedCheck.php
  app/Http/Middleware/AdminMasterCheck.php
  app/Http/Middleware/UserApproveCheck.php
  routes/api.php
Labels: ✨ Feat, 🐛 Fix

#240 Fix: 美容室メニュー関連APIの権限を調整
  routes/api.php
Labels: 🐛 Fix

#241 Fix: Userモデルのfillableを修正
  app/Models/User.php
Labels: 🐛 Fix

#243 Feat: AS関連機能を実装
  app/Http/Controllers/Admin/AdminAfterServiceController.php
  app/Http/Controllers/Admin/NoticeController.php
  app/Http/Controllers/Admin/SalonCategoryController.php
  app/Http/Controllers/Admin/SalonServiceController.php
  app/Http/Controllers/User/UserAfterServiceController.php
  app/Models/AfterService.php
  database/factories/AfterServiceFactory.php
  database/migrations/2024_01_18_080551_create_after_services_table.php
  database/seeders/AfterServiceSeeder.php
  database/seeders/DatabaseSeeder.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, ♻️ Refactor, 📝 Docs

#253 Feat: 会議室関連機能を実装
  app/Http/Controllers/MeetingRoomController.php
  app/Http/Controllers/MeetingRoomReservationController.php
  app/Models/MeetingRoom.php
  app/Models/MeetingRoomReservation.php
  database/factories/MeetingRoomReservationFactory.php
  database/migrations/2024_01_18_072535_create_meeting_rooms_table.php
  database/migrations/2024_01_18_072648_create_meeting_room_reservations_table.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, ♻️ Refactor, 📝 Docs

#261 Fix: routeエラーおよびログインエラーを解決
  app/Http/Controllers/Admin/NoticeController.php
  app/Http/Controllers/MeetingRoomReservationController.php
  app/Http/Controllers/User/UserController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 📝 Docs, 🐛 Fix

#263 Fix: googleログインエラーを修正
  app/Http/Controllers/User/UserController.php
Labels: 🐛 Fix

#264 fix: bus migration 修正
  app/Http/Controllers/BusScheduleController.php
  app/Models/BusRound.php
  app/Models/BusRoute.php
  app/Models/BusSchedule.php
  database/migrations/2024_03_04_111424_create_bus_routes_table.php
  database/migrations/2024_03_04_111500_create_bus_rounds_table.php
  database/migrations/2024_03_04_111524_create_bus_schedules_table.php
Labels: 🐛 Fix

#265 Refactor: ASを読み込む機能の修正
  app/Http/Controllers/User/UserAfterServiceController.php
Labels: ♻️ Refactor

#266 Refactor: ASを読み込む機能の修正
  app/Http/Controllers/User/UserAfterServiceController.php
  storage/api-docs/api-docs.json
Labels: ♻️ Refactor

#267 Feat: googleログイン用middlewareを実装
  app/Http/Controllers/User/UserController.php
  app/Http/Kernel.php
  app/Http/Middleware/UserGoogleApprovedCheck.php
  routes/api.php
Labels: ✨ Feat

#268 Refactor: AS機能を修正
  app/Http/Controllers/Admin/AdminAfterServiceController.php
  app/Http/Controllers/MeetingRoomController.php
  app/Http/Controllers/User/UserAfterServiceController.php
Labels: ♻️ Refactor

#269 fix: bus API 修正
  app/Http/Controllers/BusScheduleController.php
  database/migrations/2024_02_29_141433_create_bus_schedules_table.php
  routes/api.php
Labels: 🐛 Fix

#270 Fix: 会議室関連予約を解決
  app/Http/Controllers/MeetingRoomController.php
  app/Http/Controllers/MeetingRoomReservationController.php
  app/Http/Controllers/User/UserAfterServiceController.php
  database/seeders/AdminSeeder.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, 📝 Docs, 🐛 Fix

#272 Feat: 会議室の予約機能を実装
  app/Console/Commands/MakeService.php
  app/Http/Controllers/Admin/AdminAfterServiceController.php
  app/Http/Controllers/MeetingRoomController.php
  app/Http/Controllers/MeetingRoomReservationController.php
  app/Services/ReservedTimeService.php
  lang/kr/validation.php
  routes/api.php
  storage/api-docs/api-docs.json
  stubs/service.stub
Labels: ✨ Feat, ♻️ Refactor, 📝 Docs

#275 Refactor: 外泊テーブルを修正
  app/Http/Controllers/Admin/SalonServiceController.php
  app/Models/Absence.php
  app/Models/User.php
  database/migrations/2024_01_18_072736_create_stay_out_lists_table.php
  database/migrations/2024_02_29_141433_create_bus_schedules_table.php
  storage/api-docs/api-docs.json
Labels: ♻️ Refactor, 📝 Docs

#276 Feat: 外泊関連機能を実装
  app/Http/Controllers/AbsenceController.php
  app/Http/Controllers/User/UserSalonReservationController.php
  app/Models/AbsenceList.php
  app/Models/User.php
  database/migrations/2024_01_18_072736_create_absence_lists_table.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, 🚚 Rename, 📝 Docs

#277 Refactor: 会議室を読み込む機能を修正
  app/Http/Controllers/AbsenceController.php
  app/Http/Controllers/MeetingRoomController.php
  app/Http/Controllers/MeetingRoomReservationController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ♻️ Refactor, 📝 Docs, 🐛 Fix

#279 fix: bus get,patch API 修正
  app/Http/Controllers/BusScheduleController.php
  app/Http/Controllers/WeekendMealTypeController.php
  database/migrations/2024_02_21_212448_create_semester_meal_type_table.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🐛 Fix

#280 fix: migration 修正
  database/migrations/2024_01_18_072648_create_meeting_room_reservations_table.php
  database/migrations/2024_01_18_081839_create_restaurant_semesters_table.php
  database/migrations/2024_02_21_212448_create_semester_meal_types_table.php
  database/migrations/2024_02_21_212458_create_weekend_meal_types_table.php
  database/migrations/2024_02_21_212817_create_restaurant_weekend_meal_types_table.php
  database/migrations/2024_02_21_212823_create_restaurant_semester_meal_types_table.php
  routes/api.php
Labels: 🐛 Fix

#282 Refactor: routeを整理
  app/Http/Controllers/Admin/AdminAfterServiceController.php
  app/Http/Controllers/Admin/AdminSalonReservationController.php
  app/Http/Controllers/Admin/NoticeController.php
  app/Http/Controllers/Admin/SalonBreakTimeController.php
  app/Http/Controllers/Admin/SalonBusinessHourController.php
  app/Http/Controllers/Admin/SalonCategoryController.php
  app/Http/Controllers/Admin/SalonServiceController.php
  app/Http/Controllers/AfterServiceCommentController.php
  app/Http/Controllers/MeetingRoomController.php
  app/Http/Controllers/MeetingRoomReservationController.php
  app/Http/Controllers/QRController.php
  app/Http/Controllers/RestaurantMenusController.php
  app/Http/Controllers/User/UserController.php
  app/Http/Controllers/User/UserSalonReservationController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ♻️ Refactor

#284 Refactor: ファイルの整理
  app/Http/Controllers/Admin/AdminAfterServiceController.php
  app/Http/Controllers/Administrator/AbsenceController.php
  app/Http/Controllers/Administrator/BusScheduleController.php
  app/Http/Controllers/Administrator/NoticeController.php
  app/Http/Controllers/AfterService/AfterServiceCommentController.php
  app/Http/Controllers/AfterService/AfterServiceController.php
  app/Http/Controllers/Auth/AdminController.php
  app/Http/Controllers/Auth/UserController.php
  app/Http/Controllers/MeetingRoom/MeetingRoomController.php
  app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php
  app/Http/Controllers/Restaurant/RestaurantMenusController.php
  app/Http/Controllers/Restaurant/RestaurantSemesterController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  app/Http/Controllers/Restaurant/SemesterMealTypeController.php
  app/Http/Controllers/Restaurant/WeekendMealTypeController.php
  app/Http/Controllers/Salon/SalonBreakTimeController.php
  app/Http/Controllers/Salon/SalonBusinessHourController.php
  app/Http/Controllers/Salon/SalonCategoryController.php
  app/Http/Controllers/Salon/SalonReservationController.php
  app/Http/Controllers/Salon/SalonServiceController.php
  app/Http/Controllers/User/UserSalonReservationController.php
  database/seeders/DatabaseSeeder.php
  routes/api.php
Labels: ♻️ Refactor, 🚚 Rename

#285 fix: restaurant_semester_meal_type API,DB 修正
  app/Models/SemesterMealType.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🐛 Fix

#287 Refactor: 外泊関連機能を修正
  app/Http/Controllers/Administrator/AbsenceController.php
Labels: ♻️ Refactor

#289 Feat: 外泊カウント機能を実装
  app/Http/Controllers/Administrator/AbsenceController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat

#293 Refactor: 会員情報の修正機能を改善
  app/Http/Controllers/Auth/AdminController.php
  app/Http/Controllers/Auth/UserController.php
  lang/kr/validation.php
  storage/api-docs/api-docs.json
Labels: ♻️ Refactor, 📝 Docs

#294 fix: restaurant fill error
  app/Http/Controllers/Administrator/BusScheduleController.php
  app/Http/Controllers/Restaurant/RestaurantSemesterController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  app/Http/Controllers/Restaurant/SemesterMealTypeController.php
  app/Http/Controllers/Restaurant/WeekendMealTypeController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🐛 Fix

#295 Refactor: 外泊検索機能を修正
  app/Http/Controllers/Administrator/AbsenceController.php
  app/Models/SalonReservation.php
Labels: ♻️ Refactor

#296 Fix: 美容室の予約エラーを解決
  app/Models/SalonReservation.php
Labels: 🐛 Fix

#297 Fix: routeを修正
  routes/api.php
Labels: 🐛 Fix

#299 fix: bus API swagger修正
  app/Http/Controllers/Administrator/BusScheduleController.php
  routes/api.php
Labels: 🐛 Fix

#300 Refactor: 外泊検索機能を修正
  app/Http/Controllers/Administrator/AbsenceController.php
Labels: ♻️ Refactor

#302 feat: restaurant delete API 作成
  app/Http/Controllers/Restaurant/RestaurantSemesterController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  app/Http/Controllers/Restaurant/SemesterMealTypeController.php
  app/Http/Controllers/Restaurant/WeekendMealTypeController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat

#301 Refactor: 会議室の検索機能を修正
  app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php
  routes/api.php
Labels: ♻️ Refactor

#303 Feat: 既存のtokenからJWTに改善
  app/Http/Controllers/Administrator/AbsenceController.php
  app/Http/Controllers/Administrator/NoticeController.php
  app/Http/Controllers/AfterService/AfterServiceCommentController.php
  app/Http/Controllers/AfterService/AfterServiceController.php
  app/Http/Controllers/Auth/AdminController.php
  app/Http/Controllers/Auth/UserController.php
  app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php
  app/Http/Controllers/Salon/SalonReservationController.php
  app/Http/Middleware/UserGoogleApprovedCheck.php
  app/Models/Admin.php
  app/Models/User.php
  composer.json
  composer.lock
  config/auth.php
  config/jwt.php
  routes/api.php
Labels: ✨ Feat, ♻️ Refactor, 🔨 Chore

#304 fix: bus_routes migration 修正
  app/Http/Controllers/Administrator/BusScheduleController.php
  database/migrations/2024_01_18_081839_create_restaurant_semesters_table.php
  database/migrations/2024_01_18_082155_create_restaurant_weekends_table.php
  database/migrations/2024_03_04_111424_create_bus_routes_table.php
Labels: 🐛 Fix

#306 fix: bus schedule API修正
  app/Http/Controllers/Administrator/BusScheduleController.php
Labels: 🐛 Fix

#307 Refactor: tokenserviceクラスを修正
  app/Http/Controllers/Auth/AdminController.php
  app/Http/Controllers/Auth/UserController.php
  app/Services/TokenService.php
  config/jwt.php
Labels: ♻️ Refactor

#309 Feat: ユーザーのASを読み込む機能を実装
  app/Http/Controllers/AfterService/AfterServiceController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat

#310 Refactor: ユーザーのASを読み込む機能を修正
  app/Http/Controllers/AfterService/AfterServiceController.php
  config/jwt.php
Labels: 🐛 Fix

#311 Refactor: AS関連機能を修正
  app/Http/Controllers/AfterService/AfterServiceController.php
Labels: ♻️ Refactor

#312 fix: restaurant semester API 修正
  app/Http/Controllers/Restaurant/RestaurantSemesterController.php
Labels: 🐛 Fix

#313 fix: restaurant menu migration 修正
  app/Http/Controllers/Restaurant/RestaurantMenusController.php
  app/Models/BusRoute.php
  app/Models/RestaurantMenu.php
  app/Models/RestaurantMenuMonth.php
  database/migrations/2024_03_07_203208_create_restaurant_menu_months_table.php
  database/migrations/2024_03_11_193806_create_restaurant_menus_table.php
  storage/api-docs/api-docs.json
Labels: 🐛 Fix

#314 Refactor: HTTPステータスコードを変更
  app/Http/Middleware/UserApproveCheck.php
  app/Http/Middleware/UserGoogleApprovedCheck.php
Labels: ♻️ Refactor

#315 Refactor: ASおよび、美容室関連機能を修正
  app/Http/Controllers/AfterService/AfterServiceController.php
  app/Http/Controllers/Salon/SalonReservationController.php
Labels: ♻️ Refactor

#317 Refactor: ユーザー認証関連機能の修正
  app/Http/Controllers/Auth/AdminController.php
  app/Http/Controllers/Auth/UserController.php
  app/Http/Controllers/RefreshController.php
  app/Http/Kernel.php
  app/Http/Middleware/AdminMasterCheck.php
  app/Http/Middleware/Authenticate.php
  app/Http/Middleware/TokenType.php
  app/Providers/AuthServiceProvider.php
  app/Providers/CustomUserProvider.php
  app/Services/TokenService.php
  config/auth.php
  config/jwt.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, ♻️ Refactor, 🐛 Fix

#319 Feat: 3件のnoticeを読み込む機能を実装
  app/Http/Controllers/Administrator/NoticeController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, 📝 Docs

#320 fix: bus, restaurant API, migration 修正
  app/Http/Controllers/Administrator/BusScheduleController.php
  app/Http/Controllers/Restaurant/RestaurantMenusController.php
  app/Imports/RestaurantMenuImport.php
  app/Models/RestaurantMenu.php
  app/Models/RestaurantMenuDate.php
  database/migrations/2024_03_04_111524_create_bus_schedules_table.php
  database/migrations/2024_03_07_203208_create_restaurant_menu_dates_table.php
  database/migrations/2024_03_11_193806_create_restaurant_menus_table.php
  routes/api.php
Labels: 🐛 Fix

#321 Refactor: ユーザーのASを読み込む機能を修正
  app/Http/Controllers/AfterService/AfterServiceController.php
Labels: ♻️ Refactor

#323 Fix: AS関連機能を修正
  app/Http/Controllers/AfterService/AfterServiceController.php
  routes/api.php
Labels: ♻️ Refactor, 🐛 Fix

#324 Feat: トークンのタイプをチェックするミドルウェアを実装
  app/Http/Middleware/TokenType.php
  routes/api.php
Labels: ✨ Feat

#325 Refactor: 美容室のrouteを修正
  routes/api.php
Labels: ♻️ Refactor

#326 feat: restaurant_menu month,day Get 作成
  app/Http/Controllers/Administrator/BusScheduleController.php
  app/Http/Controllers/Restaurant/RestaurantMenusController.php
  app/Http/Controllers/Restaurant/RestaurantSemesterController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  app/Models/RestaurantSemester.php
  app/Models/RestaurantWeekend.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat

#327 Fix: 美容室関連機能のエラーを解決
  app/Http/Controllers/Salon/SalonBreakTimeController.php
Labels: 🐛 Fix

#330 Refactor: controllerクラスのautorizeメソッドをカスタム
  app/Http/Controllers/Administrator/AbsenceController.php
  app/Http/Controllers/Administrator/NoticeController.php
  app/Http/Controllers/AfterService/AfterServiceCommentController.php
  app/Http/Controllers/AfterService/AfterServiceController.php
  app/Http/Controllers/MeetingRoom/MeetingRoomController.php
  app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php
  app/Http/Controllers/Salon/SalonBreakTimeController.php
  app/Http/Controllers/Salon/SalonBusinessHourController.php
  app/Http/Controllers/Salon/SalonCategoryController.php
  app/Http/Controllers/Salon/SalonReservationController.php
  app/Http/Controllers/Salon/SalonServiceController.php
  config/auth.php
Labels: ♻️ Refactor

#331 Fix: refreshエラーを解決
  app/Http/Controllers/RefreshController.php
Labels: 🐛 Fix

#332 Fix: refreshエラーをおよにrouteエラー解決
  app/Http/Controllers/RefreshController.php
  app/Services/TokenService.php
  routes/api.php
Labels: 🐛 Fix

#333 Fix: 美容室予約キャンセルエラーを解決
  routes/api.php
Labels: 🐛 Fix

#334 bus_round and schedule API 作成
  app/Http/Controllers/Administrator/BusScheduleController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat

#335 Refactor: 予約された会議室の時間をソーティングするように修正
  app/Services/ReservedTimeService.php
Labels: ♻️ Refactor

#339 Chore: jwtの設定を変更
  config/jwt.php
Labels: 🔨 Chore

#340 Refactor: コントローラーのコメント作成および修正
  app/Http/Controllers/Administrator/AbsenceController.php
  app/Http/Controllers/Administrator/NoticeController.php
  app/Http/Controllers/AfterService/AfterServiceCommentController.php
  app/Http/Controllers/AfterService/AfterServiceController.php
  app/Http/Controllers/Auth/AdminController.php
  app/Http/Controllers/Auth/UserController.php
  app/Http/Controllers/Controller.php
  app/Http/Controllers/MeetingRoom/MeetingRoomController.php
  app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php
  app/Http/Controllers/RefreshController.php
  app/Http/Controllers/Salon/SalonBreakTimeController.php
  app/Http/Controllers/Salon/SalonBusinessHourController.php
  app/Http/Controllers/Salon/SalonCategoryController.php
  app/Http/Controllers/Salon/SalonReservationController.php
  app/Http/Controllers/Salon/SalonServiceController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ♻️ Refactor, 📝 Docs

#341 feat: restaurant_menu week API 追加
  app/Http/Controllers/Restaurant/RestaurantMenusController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  app/Http/Controllers/Restaurant/SemesterMealTypeController.php
  app/Imports/RestaurantMenuImport.php
  app/Models/RestaurantMenu.php
  app/Models/RestaurantMenuDate.php
  database/migrations/2024_03_07_203208_create_restaurant_menu_dates_table.php
  database/migrations/2024_03_11_193806_create_restaurant_menus_table.php
  routes/api.php
Labels: ✨ Feat

#342 Fix: vaildationエラーを修正
  app/Http/Controllers/Auth/UserController.php
  storage/api-docs/api-docs.json
Labels: 🐛 Fix

#343 Fix: 美容室のカテゴリ生成エラーを解決
  app/Http/Controllers/Salon/SalonCategoryController.php
Labels: 🐛 Fix

#344 fix: bus API error message
  app/Http/Controllers/Administrator/BusScheduleController.php
Labels: 🐛 Fix

#345 Fix: 管理者権限変更機能のエラー解決
  app/Http/Controllers/Auth/AdminController.php
Labels: 🐛 Fix

#346 feat: restaurant meal_type Get API追加
  app/Http/Controllers/Restaurant/RestaurantSemesterController.php
  app/Http/Controllers/Restaurant/SemesterMealTypeController.php
  app/Http/Controllers/Restaurant/WeekendMealTypeController.php
  routes/api.php
Labels: ✨ Feat

#347 Chore: buildspec.ymlを生成
  app/Http/Controllers/Salon/SalonServiceController.php
  buildspec.yml
  storage/api-docs/api-docs.json
Labels: 🐛 Fix, 🔨 Chore

#348 Chore: buildspec.ymlを修正
  buildspec.yml
Labels: 🔨 Chore

#350 Chore: buildspec.ymlを修正 & imagedefinitions.jsonを生成
  buildspec.yml
  imagedefinitions.json
Labels: 🔨 Chore

#351 Fix: 美容室サービス修正エラーを解決
  app/Http/Controllers/Salon/SalonServiceController.php
Labels: 🐛 Fix

#352 Chore: Dockerfileを修正
  Dockerfile
Labels: 🔨 Chore

#353 Chore: Dockerfileを修正
  Dockerfile
  routes/api.php
Labels: 🔨 Chore

#354 feat: restaurant apply list Get API 制作
  app/Http/Controllers/Restaurant/RestaurantSemesterController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  app/Http/Controllers/Restaurant/WeekendMealTypeController.php
  app/Http/Resources/SemesterApplyResource.php
  app/Http/Resources/WeekendApplyResource.php
  app/Models/RestaurantSemester.php
  app/Models/RestaurantWeekend.php
  database/migrations/2024_02_21_212458_create_weekend_meal_types_table.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat

#355 Refactor:美容室と会議室関連機能の修正
  app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php
  app/Http/Controllers/Salon/SalonServiceController.php
  app/Policies/SalonBreakTimePolicy.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ♻️ Refactor, 🐛 Fix

#356 fix: bus API error message 修正
  app/Http/Controllers/Administrator/BusScheduleController.php
Labels: 🐛 Fix

#357 Refactor: 美容室関連機能の修正
  app/Http/Controllers/Salon/SalonBusinessHourController.php
  app/Http/Controllers/Salon/SalonCategoryController.php
  storage/api-docs/api-docs.json
Labels: ♻️ Refactor

#358 Test: codepipelineテスト
  resources/views/welcome.blade.php
Labels: 🧪 Test

#359 Test: codepipelineテスト
  codepipeline.md
Labels: 🧪 Test

#360 fix:restaurant user_id 修正
  app/Http/Controllers/Restaurant/RestaurantSemesterController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
Labels: 🐛 Fix

#361 Migrate: 美容室の営業時間テーブルを修正
  app/Http/Controllers/Salon/SalonBusinessHourController.php
  app/Models/MeetingRoomReservation.php
  database/migrations/2024_02_17_164259_create_salon_business_hours_table.php
  database/seeders/SalonBusinessHourSeeder.php
  routes/api.php
Labels: ♻️ Refactor

#362 Test: codepipelineのテスト
  codepipeline.md
Labels: 🧪 Test

#364 Chore: appspec.yamlを作成
  appspec.yaml
Labels: 🔨 Chore

#365 fix: restaurant API store,show 修正
  app/Http/Controllers/Restaurant/RestaurantSemesterController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  app/Http/Resources/WeekendApplyResource.php
  app/Models/RestaurantWeekend.php
  app/Models/RestaurantWeekendMealType.php
  app/Models/WeekendMealType.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🐛 Fix

#367 Refactor: 連関関係を修正
  app/Http/Controllers/AfterService/AfterServiceController.php
Labels: ♻️ Refactor

#368 Rename: yamlからymlに修正
  appspec.yml
Labels: 🚚 Rename

#369 Fix: ASのコメント削除エラーを解決
  app/Http/Controllers/AfterService/AfterServiceCommentController.php
Labels: 🐛 Fix

#371 fix:auth user_id 修正
  database/migrations/2024_03_07_203208_create_restaurant_menu_dates_table.php
  routes/api.php
Labels: 🐛 Fix

#373 fix:auth user_id 2修正
  app/Http/Controllers/Restaurant/RestaurantSemesterController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  routes/api.php
Labels: 🐛 Fix

#374 Chore: buildspec.ymlを修正
  buildspec.yml
Labels: 🔨 Chore

#375 Chore: taskdef.jsonを生成
  appspec.yml
  taskdef.json
Labels: 🔨 Chore

#376 Refactor: 会議室の予約時間関連機能の修正
  app/Services/ReservedTimeService.php
Labels: ♻️ Refactor

#377 Chore: taskdef.jsonを修正
  taskdef.json
Labels: 🔨 Chore

#378 Chore: appspec.ymlを修正
  appspec.yml
Labels: 🔨 Chore

#379 fix:restaurant API swagger修正
  app/Http/Controllers/Administrator/BusScheduleController.php
  app/Http/Controllers/Restaurant/RestaurantMenusController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  app/Http/Controllers/Restaurant/SemesterMealTypeController.php
  app/Http/Controllers/Restaurant/WeekendMealTypeController.php
  app/Models/RestaurantApplySetting.php
  database/migrations/2024_03_19_112600_create_restaurant_apply_settings_table.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🐛 Fix

#380 fix: restaurant user_id ex
  app/Http/Controllers/Restaurant/RestaurantSemesterController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
Labels: 🐛 Fix

#381 Chore: nginx関連ファイルを修正
  Dockerfile.nginx
  nginx/default.conf
Labels: 🔨 Chore

#382 fix:restaurant user_id 修正
  app/Http/Controllers/Restaurant/RestaurantSemesterController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  database/migrations/2024_03_19_112600_create_restaurant_apply_settings_table.php
  routes/api.php
Labels: 🐛 Fix

#383 fix:restaurant user_id 修正
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
  app/Http/Controllers/Restaurant/RestaurantApplySettingController.php
  app/Http/Controllers/Restaurant/RestaurantSemesterController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  app/Models/RestaurantApplyManual.php
  app/Models/RestaurantSemesterAuto.php
  app/Models/RestaurantWeekendAuto.php
  database/migrations/2024_03_19_231519_create_restaurant_weekend_autos_table.php
  database/migrations/2024_03_19_232048_create_restaurant_apply_manuals_table.php
  database/migrations/2024_03_20_004245_create_restaurant_semester_autos_table.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🐛 Fix

#384 Feat: 管理者およびユーザーの情報を読み込む機能を実装
  app/Http/Controllers/Auth/AdminController.php
  app/Http/Controllers/Auth/UserController.php
  database/migrations/2024_01_29_070101_create_salon_reservations_table.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, 📝 Docs

#385 Fix: 美容室の営業直関連エラーを解決
  app/Http/Controllers/Controller.php
  app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php
Labels: 🐛 Fix

#386 fix:restaurant_Apply_division API swagger修正
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
  app/Http/Controllers/Restaurant/RestaurantSemesterController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  app/Models/RestaurantSemester.php
  storage/api-docs/api-docs.json
Labels: 🐛 Fix

#388 fix:restaurant_meal_type get API 修正
  app/Http/Controllers/Administrator/BusScheduleController.php
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
  app/Http/Controllers/Restaurant/RestaurantSemesterController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  app/Http/Controllers/Restaurant/SemesterMealTypeController.php
  app/Http/Controllers/Restaurant/WeekendMealTypeController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🐛 Fix

#389 feat:restaurant_apply get API 作成
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat

#390 feat:restaurant_apply App get API 作成
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat

#391 Chore: nginx関連ファイルを修正
  Dockerfile.nginx
  nginx/default.conf
  storage/api-docs/api-docs.json
Labels: 🔨 Chore

#392 Fix: 美容室検索エラーを解決
  app/Models/SalonReservation.php
Labels: 🐛 Fix

#393 Fix: noticeの削除エラーを解決
  app/Policies/NoticePolicy.php
Labels: 🐛 Fix

#396 fix:restaurant_show API 修正
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
  app/Http/Controllers/Restaurant/RestaurantSemesterController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  routes/api.php
Labels: 🐛 Fix

#397 fix:restaurant_user_show API 修正
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
  app/Http/Controllers/Restaurant/RestaurantSemesterController.php
  routes/api.php
Labels: 🐛 Fix

#398 fix:restaurant_apply_division API, db 修正
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
  app/Models/RestaurantApplyManual.php
  app/Models/RestaurantApplySetting.php
  app/Models/RestaurantSemesterAuto.php
  app/Models/RestaurantWeekendAuto.php
  database/migrations/2024_03_19_231519_create_restaurant_weekend_autos_table.php
  database/migrations/2024_03_19_232048_create_restaurant_apply_manuals_table.php
  database/migrations/2024_03_20_004245_create_restaurant_semester_autos_table.php
  storage/api-docs/api-docs.json
Labels: 🐛 Fix

#399 Refactor: ASのコメント関連機能を実装
  app/Http/Controllers/AfterService/AfterServiceCommentController.php
  app/Http/Controllers/AfterService/AfterServiceController.php
  app/Http/Controllers/Salon/SalonServiceController.php
  app/Models/AfterServiceComment.php
  database/migrations/2024_01_18_081604_create_after_service_comments_table.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, ♻️ Refactor, 📝 Docs

#400 Refactor: googleログイン機能を修正
  app/Http/Controllers/Auth/UserController.php
  composer.json
  composer.lock
Labels: ♻️ Refactor, 🔨 Chore

#401 fix:restaurant_menu_dates 修正
  database/migrations/2024_03_07_203208_create_restaurant_menu_dates_table.php
Labels: 🐛 Fix

#403 Feat: 会議室を閉じる機能を実装
  app/Http/Controllers/MeetingRoom/MeetingRoomController.php
  app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php
  app/Models/MeetingRoom.php
  database/migrations/2024_01_18_072535_create_meeting_rooms_table.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, ♻️ Refactor, 📝 Docs

#405 Refactor: 管理者のログイン機能を改善
  app/Http/Controllers/Auth/AdminController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ♻️ Refactor, 📝 Docs

#406 feat:restaurant account table,API 作成
  app/Http/Controllers/Restaurant/RestaurantAccountController.php
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  app/Models/RestaurantAccount.php
  app/Models/RestaurantApplyState.php
  database/migrations/2024_03_21_132216_create_restaurant_apply_states_table.php
  database/migrations/2024_03_25_193642_create_restaurant_accounts_table.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat

#408 Refactor: approveの可否をチェックするmiddlewareを修正
  app/Http/Kernel.php
  app/Http/Middleware/AdminApprovedCheck.php
  app/Http/Middleware/AdminLoginApproveCheck.php
  app/Http/Middleware/AdminMasterCheck.php
  app/Http/Middleware/ApproveCheck.php
  routes/api.php
Labels: 🔥 Remove, ♻️ Refactor

#409 Fix: approveをチェックするmiddlewareを削除
  routes/api.php
Labels: 🚑 !HOTFIX

#410 fix:restaurant account,meal_type API 修正
  app/Http/Controllers/Restaurant/RestaurantAccountController.php
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
  app/Http/Controllers/Restaurant/SemesterMealTypeController.php
  app/Http/Controllers/Restaurant/WeekendMealTypeController.php
  app/Models/RestaurantAccount.php
  database/migrations/2024_03_25_193642_create_restaurant_accounts_table.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🐛 Fix

#411 Fix: approveをチェックするmiddlewareを修正/適用
  app/Http/Middleware/ApproveCheck.php
  app/Providers/AuthServiceProvider.php
  config/auth.php
  routes/api.php
Labels: ♻️ Refactor, 🐛 Fix

#412 fix:bus_schedules API 修正
  app/Http/Controllers/Administrator/BusScheduleController.php
  app/Http/Controllers/Restaurant/RestaurantMenusController.php
  app/Imports/RestaurantMenuImport.php
  database/seeders/BusRouteSeeder.php
  database/seeders/RestaurantMenuDateSeeder.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🐛 Fix

#413 fix:restaurant apply user API 修正
  app/Http/Controllers/Administrator/BusScheduleController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🐛 Fix

#414 Feat: 管理者のパスワードリセット機能を実装
  app/Http/Controllers/Auth/AdminController.php
  app/Mail/ResetPassword.php
  app/Models/PasswordResetCode.php
  composer.json
  composer.lock
  config/mail.php
  database/migrations/2024_03_26_161131_create_password_reset_codes_table.php
  resources/views/mail/password.blade.php
  routes/api.php
Labels: ✨ Feat, 🔨 Chore

#416 Feat: ユーザーのパスワードリセット機能を実装
  app/Http/Controllers/Auth/AdminController.php
  app/Http/Controllers/Auth/UserController.php
  app/Http/Controllers/PasswordResetCodeController.php
  config/jwt.php
  routes/api.php
Labels: ✨ Feat, ♻️ Refactor

#417 Refactor: パスワードをリセットする機能を改善
  app/Http/Controllers/Auth/AdminController.php
  app/Http/Controllers/Auth/UserController.php
  app/Http/Controllers/PasswordResetCodeController.php
  database/migrations/2024_03_26_161131_create_password_reset_codes_table.php
Labels: ♻️ Refactor

#420 Feat: 最新の緊急お知らせを読み込む機能を実装
  app/Http/Controllers/Administrator/NoticeController.php
  routes/api.php
Labels: ✨ Feat

#421 Docs: API文書を修正
  app/Http/Controllers/Administrator/NoticeController.php
  storage/api-docs/api-docs.json
Labels: 📝 Docs

#422 Feat: パスワードをリセットするサービスを実装
  app/Services/ResetPasswordService.php
Labels: ✨ Feat, 🐛 Fix

#423 HOTFIX: APIエラーを解決
  app/Http/Middleware/Authenticate.php
  config/auth.php
  routes/api.php
Labels: 🚑 !HOTFIX

#427 Fix: refreshエラーを解決
  app/Http/Controllers/RefreshController.php
Labels: 🐛 Fix

#428 Refactor: 管理者の認証関連機能を修正
  app/Http/Controllers/Auth/AdminController.php
  app/Http/Middleware/AdminMasterCheck.php
  app/Models/User.php
  config/jwt.php
  storage/api-docs/api-docs.json
Labels: ♻️ Refactor, 🐛 Fix, 🔨 Chore

#429 Fix: 管理者関連機能のエラーを解決
  app/Http/Controllers/Auth/AdminController.php
Labels: 🐛 Fix

#430 feat:restaurant_weekend sumApplyWeb 作成
  app/Http/Controllers/Restaurant/RestaurantAccountController.php
  app/Http/Controllers/Restaurant/RestaurantSemesterController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat

#432 Fix: 会議室の修正機能のエラーを解決
  routes/api.php
Labels: 🐛 Fix

#433 Refactor: adminのメール確認機能を削除
  app/Http/Controllers/Auth/AdminController.php
  app/Http/Controllers/Auth/UserController.php
  app/Http/Controllers/Controller.php
  routes/api.php
Labels: ♻️ Refactor, 🐛 Fix

#434 Refactor: 外泊申請機能のHTTPステータスコードを変更
  app/Http/Controllers/Administrator/AbsenceController.php
  storage/api-docs/api-docs.json
Labels: ♻️ Refactor

#435 Refactor: 新しいユーザーテーブルに合わせてpolicyを修正
  app/Policies/AbsenceListPolicy.php
  app/Policies/AfterServiceCommentPolicy.php
  app/Policies/AfterServicePolicy.php
  app/Policies/MeetingRoomPolicy.php
  app/Policies/MeetingRoomReservationPolicy.php
  app/Policies/NoticePolicy.php
  app/Policies/SalonBreakTimePolicy.php
  app/Policies/SalonBusinessHourPolicy.php
  app/Policies/SalonCategoryPolicy.php
  app/Policies/SalonReservationPolicy.php
  app/Policies/SalonServicePolicy.php
  routes/api.php
Labels: ♻️ Refactor

#436 Refactor: master権限のpolicyを適用
  app/Http/Controllers/Auth/AdminController.php
  app/Http/Kernel.php
  app/Http/Middleware/AdminLoginApproveCheck.php
  app/Http/Middleware/AdminMasterCheck.php
  app/Http/Middleware/LoginApproveCheck.php
  app/Policies/AdminPolicy.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🔥 Remove, ♻️ Refactor, 🚚 Rename

#438 fix:restaurant_apply_division API 修正
  app/Http/Controllers/Restaurant/RestaurantApplyDivisionController.php
  app/Http/Controllers/Restaurant/RestaurantWeekendController.php
  app/Imports/RestaurantMenuImport.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🐛 Fix

#440 Refactor: 全体コード改善
  app/Http/Controllers/Administrator/NoticeController.php
  app/Http/Controllers/AfterService/AfterServiceCommentController.php
  app/Http/Controllers/AfterService/AfterServiceController.php
  app/Http/Controllers/Auth/AdminController.php
  app/Http/Controllers/Auth/UserController.php
  app/Http/Controllers/MeetingRoom/MeetingRoomReservationController.php
  app/Http/Controllers/Salon/SalonBusinessHourController.php
  app/Http/Controllers/Salon/SalonReservationController.php
  app/Http/Controllers/Salon/SalonServiceController.php
  storage/api-docs/api-docs.json
Labels: ♻️ Refactor

#442 Feat: 権限のリストを読み込む機能を実装
  app/Http/Controllers/Auth/PasswordResetCodeController.php
  app/Http/Controllers/Auth/PrivilegeController.php
  app/Http/Controllers/Auth/RefreshController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, 🚚 Rename, 📝 Docs

#443 Fix: エラーを解決
  app/Http/Controllers/Auth/AdminController.php
  app/Http/Controllers/Salon/SalonBreakTimeController.php
  app/Http/Controllers/Salon/SalonBusinessHourController.php
  app/Http/Controllers/Salon/SalonCategoryController.php
  app/Http/Controllers/Salon/SalonReservationController.php
  app/Http/Controllers/Salon/SalonServiceController.php
Labels: 🐛 Fix

#444 Feat: パスワードリセットトークンおよびパスワード再設定機能を実装
  app/Http/Controllers/AfterService/AfterServiceController.php
  app/Http/Controllers/Auth/AdminController.php
  app/Http/Controllers/Auth/PasswordResetCodeController.php
  app/Http/Controllers/Auth/RefreshController.php
  app/Http/Controllers/Auth/UserController.php
  app/Services/TokenService.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, ♻️ Refactor, 📝 Docs, 🐛 Fix
