Repository Shining-Jicheon-Stars/yjg-laravel-backend, pull requests merged in 2024-01, with the labels that each got.

#2 Feat : Create migration file
  database/migrations/2024_01_18_071727_create_notices.php
  database/migrations/2024_01_18_072030_create_notice_images.php
  database/migrations/2024_01_18_072139_create_salon_reservations.php
  database/migrations/2024_01_18_072410_create_salon_menu.php
  database/migrations/2024_01_18_072535_create_meeting_room_reservations.php
  database/migrations/2024_01_18_072648_create_meeting_rooms.php
  database/migrations/2024_01_18_072736_create_sleepover_lists.php
  database/migrations/2024_01_18_072851_create_bus_times.php
Labels: ✨ Feat

#8 Feat: モデル作成
  app/Http/Kernel.php
  app/Models/AfterService.php
  app/Models/AfterServiceComment.php
  app/Models/AfterServiceImage.php
  app/Models/RestaurantMenu.php
  app/Models/RestaurantSemester.php
  app/Models/RestaurantWeekend.php
  app/Models/User.php
  composer.json
  composer.lock
  database/migrations/2024_01_18_072410_create_salon_reservations_table.php
  database/migrations/2024_01_18_080008_create_restaurant_menus_table.php
  database/migrations/2024_01_18_080551_create_after_services_table.php
  database/migrations/2024_01_18_081604_create_after_service_comments_table.php
Labels: ✨ Feat

#9 Feat: モデル作成
  app/Models/MeetingRoom.php
  app/Models/MeetingRoomReservation.php
  app/Models/Notice.php
  app/Models/NoticeImage.php
  app/Models/SalonMenu.php
  app/Models/SalonReservation.php
  app/Models/SleepoverList.php
Labels: ✨ Feat

#10 Feat: 会員登録、脱退機能追加
  app/Exceptions/DestroyException.php
  app/Http/Controllers/Controller.php
  app/Http/Controllers/UserController.php
  composer.json
  composer.lock
  config/app.php
  config/l5-swagger.php
  resources/views/vendor/l5-swagger/.gitkeep
  resources/views/vendor/l5-swagger/index.blade.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat

#20 Feat: 管理者の権限付与機能実装
  app/Http/Controllers/AdminController.php
  app/Models/Admin.php
  database/migrations/2024_01_25_101725_create_admins_table.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat

#21 Feat: パスワード、メール確認実装
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/Controller.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat

#27 Refactor: HTTPステータスコード変更
  app/Http/Controllers/AdminController.php
Labels: ♻️ Refactor

#29 !HOTFIX: CORSエラー解決
  app/Http/Kernel.php
  config/auth.php
  config/cors.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2024_01_25_101725_create_admins_table.php
Labels: ♻️ Refactor, 🚑 !HOTFIX, 🐛 Fix, 🔨 Chore

#32 Fix: メール確認機能エラー解決
  app/Http/Controllers/AdminController.php
  app/Models/Admin.php
  routes/api.php
Labels: 🐛 Fix

#33 !HOTFIX: Update Dockerfile
  Dockerfile
Labels: 🚑 !HOTFIX
