Repository Shining-Jicheon-Stars/yjg-laravel-backend, pull requests merged in 2024-02, with the labels that each got.

#53 Fix: ログアウトエラー解決
  app/Http/Controllers/AdminController.php
  config/auth.php
  config/sanctum.php
  database/migrations/2024_01_18_082155_create_restaurant_weekends_table.php
  resources/js/bootstrap.js
Labels: ✨ Feat, 🐛 Fix

#58 Feat: メール検索実装
  app/Http/Controllers/AdminController.php
  database/factories/AdminFactory.php
  database/migrations/2024_01_25_101725_create_admins_table.php
  database/seeders/AdminTestSeeder.php
  database/seeders/DatabaseSeeder.php
  routes/api.php
  storage/api-docs/api-docs.json
  tests/Feature/AdminTest.php
  tests/TestCase.php
Labels: ✨ Feat, ♻️ Refactor, 🐛 Fix

#59 Feat: 学生ユーザー関連機能実装
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/Controller.php
  app/Http/Controllers/UserController.php
  config/sanctum.php
  config/services.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2024_01_18_082155_create_restaurant_weekends_table.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, 📝 Docs, 🐛 Fix

#62 Feat: G suiteメールだけを許可する機能実装
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/UserController.php
Labels: ✨ Feat

#68 Feat: 外国人会員登録、ログイン機能実装
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/UserController.php
  database/migrations/2014_10_12_000000_create_users_table.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat

#72 Feat: 美容室関連機能実装
  app/Http/Controllers/SalonCategoryController.php
  app/Http/Controllers/SalonReservationController.php
  app/Http/Controllers/SalonServiceController.php
  app/Models/Admin.php
  app/Models/SalonCategory.php
  app/Models/SalonPrice.php
  app/Models/SalonReservation.php
  app/Models/SalonService.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, 📝 Docs, 🐛 Fix

#73 Refactor:　プロジェクトの構造とAPIのURL変更
  app/Http/Controllers/Admin/AdminController.php
  app/Http/Controllers/Admin/AdminSalonCategoryController.php
  app/Http/Controllers/Admin/AdminSalonReservationController.php
  app/Http/Controllers/Admin/AdminSalonServiceController.php
  app/Http/Controllers/User/AuthController.php
  app/Http/Controllers/User/UserController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ♻️ Refactor

#75 Remove: CODEOWNERSを削除
  .github/CODEOWNERS
Labels: 🔥 Remove

#81 Test: Assignee自動化テスト
  .github/CODEOWNERS
  auto_assign_test.md
Labels: ✨ Feat, 🧪 Test

#83 Test: Assignees自動化テスト
  .github/CODEOWNERS
  auto_assign_test.md
Labels: 🧪 Test

#85 Test: Reviewerテスト
  auto_assign_test.md
Labels: 🧪 Test

#107 Test: auto_assignテスト
  auto_assign_test.md
Labels: 🧪 Test

#108 Fix: 予約機能改善
  app/Http/Controllers/Admin/AdminSalonReservationController.php
Labels: 🐛 Fix

#116 Fix: 管理者検索機能エラー解決
  app/Http/Controllers/Admin/AdminController.php
  app/Http/Controllers/Admin/AdminSalonReservationController.php
  database/migrations/2024_01_18_080008_create_restaurant_menus_table.php
  storage/api-docs/api-docs.json
Labels: ♻️ Refactor, 📝 Docs, 🐛 Fix

#119 Migration: salon_reservationsスキーマ変更
  app/Models/SalonReservation.php
  database/migrations/2024_01_29_070101_create_salon_reservations_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/SalonSeeder.php
Labels: ✨ Feat

#122 Chore: Socialiteをアップデート
  composer.json
  composer.lock
Labels: 🔨 Chore

#123 Chore: CODEOWNERSを修正
  .github/CODEOWNERS
Labels: 🔨 Chore

#125 Fix: メールチェック機能エラー解決
  app/Http/Controllers/Admin/AdminController.php
Labels: ✨ Feat

#127 Fix: 管理者リスト機能修正
  app/Http/Controllers/Admin/AdminController.php
Labels: 🐛 Fix

#129 Fix:QRControllerを修正
  app/Http/Controllers/QRController.php
  routes/api.php
Labels: 🐛 Fix

#130 Feat: 美容室関連機能実装
  app/Http/Controllers/Admin/AdminController.php
  app/Http/Controllers/Admin/AdminSalonCategoryController.php
  app/Http/Controllers/Admin/AdminSalonServiceController.php
  app/Http/Controllers/User/UserController.php
  app/Http/Controllers/User/UserSalonReservationController.php
  composer.json
  composer.lock
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, ♻️ Refactor, 📝 Docs

#142 Feat: 美容室の営業時間関連機能実装
  app/Http/Controllers/Admin/AdminSalonReservationController.php
  app/Http/Controllers/Admin/SalonBreakTimeController.php
  app/Http/Controllers/Admin/SalonBusinessHourController.php
  app/Http/Controllers/User/UserController.php
  app/Http/Controllers/User/UserSalonReservationController.php
  app/Models/SalonBreakTime.php
  app/Models/SalonBusinessHour.php
  database/migrations/2024_01_18_072648_create_meeting_room_reservations_table.php
  database/migrations/2024_01_18_080008_create_restaurant_menus_table.php
  database/migrations/2024_01_18_080551_create_after_services_table.php
  database/migrations/2024_01_18_081448_create_after_service_images_table.php
  database/migrations/2024_01_18_081604_create_after_service_comments_table.php
  database/migrations/2024_01_24_104549_create_after_service_images_after_service_table.php
  database/migrations/2024_01_29_070101_create_salon_reservations_table.php
  database/migrations/2024_02_17_164313_create_salon_break_times_table.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, ♻️ Refactor, 📝 Docs, 🐛 Fix

#147 Migration: 美容室サービス関連テーブルを修正
  app/Http/Controllers/Admin/SalonCategoryController.php
  app/Http/Controllers/User/UserController.php
  app/Models/SalonPrice.php
  app/Models/SalonReservation.php
  app/Models/SalonService.php
  database/migrations/2024_01_29_070028_create_salon_services_table.php
  database/migrations/2024_01_29_070035_create_salon_prices_table.php
  database/migrations/2024_01_29_070101_create_salon_reservations_table.php
  routes/api.php
Labels: ✨ Feat, 🐛 Fix

#151 Feat: ユーザーのメール確認機能実装
  .gitignore
  app/Http/Controllers/Admin/AdminController.php
  app/Http/Controllers/Admin/AdminSalonReservationController.php
  app/Http/Controllers/Admin/SalonServiceController.php
  app/Http/Controllers/User/UserController.php
  app/Http/Controllers/User/UserSalonReservationController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, ♻️ Refactor, 📝 Docs, 🔨 Chore

#152 Refactor: validationルールを修正
  app/Http/Controllers/Admin/AdminController.php
  app/Http/Controllers/Controller.php
  app/Http/Controllers/User/UserController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ♻️ Refactor, 📝 Docs

#154 Fix: API文書関連エラー解決
  app/Http/Controllers/Admin/AdminController.php
  app/Http/Controllers/User/UserController.php
Labels: 🐛 Fix

#155 Feat: 美容室営業時間関連機能実装
  app/Http/Controllers/Admin/AdminSalonReservationController.php
  app/Http/Controllers/Admin/SalonBreakTimeController.php
  app/Http/Controllers/Admin/SalonBusinessHourController.php
  app/Http/Controllers/Controller.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, 📝 Docs

#160 Feat: TimeCastを適用
  app/Http/Controllers/Admin/AdminSalonReservationController.php
  app/Http/Controllers/Admin/SalonServiceController.php
  routes/api.php
Labels: ✨ Feat, ♻️ Refactor

#161 Develop
  app/Http/Controllers/QRController.php
  app/Http/Controllers/RestaurantSemesterController.php
  app/Http/Controllers/RestaurantWeekendController.php
  app/Imports/RestaurantMenuImport.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, 🐛 Fix

#165 Feat: Seederを実装
  app/Http/Controllers/Admin/SalonBusinessHourController.php
  app/Http/Controllers/Controller.php
  app/Imports/UsersImport.php
  database/seeders/DatabaseSeeder.php
  database/seeders/SalonBusinessHourSeeder.php
  database/seeders/UserSeeder.php
Labels: ✨ Feat, 🐛 Fix

#166 Feat: 韓国語のvalidationメッセージファイルを生成
  app/Http/Controllers/Admin/AdminController.php
  app/Http/Controllers/Admin/SalonBusinessHourController.php
  app/Http/Controllers/User/UserSalonReservationController.php
  config/app.php
  lang/kr/validation.php
Labels: ✨ Feat, ♻️ Refactor

#167 Develop
  app/Http/Controllers/RestaurantMealTypeController.php
  app/Models/RestaurantMealType.php
  app/Models/RestaurantMenu.php
  database/migrations/2024_02_21_061323_create_restaurant_meal_types_table.php
  routes/api.php
Labels: ✨ Feat

#173 Chore: Issueにassignees自動化実装
  .github/workflows/issue_assignee.yml
  .github/workflows/main.yml
Labels: 🔨 Chore

#180 Fix: ログインAPIメソッドエラーを解決
  routes/api.php
Labels: 🐛 Fix

#183 Migration: 行政関連マイグレーションファイル修正
  app/Models/AfterService.php
  app/Models/MeetingRoomReservation.php
  app/Models/StayOutList.php
  database/migrations/2024_01_18_071727_create_notices.php
  database/migrations/2024_01_18_072648_create_meeting_room_reservations_table.php
  database/migrations/2024_01_18_072736_create_stay_out_lists_table.php
  database/migrations/2024_01_18_080551_create_after_services_table.php
  database/migrations/2024_01_18_081448_create_after_service_images_table.php
  database/migrations/2024_01_24_104549_create_after_service_images_after_service_table.php
  database/migrations/2024_02_21_212458_create_weekend_meal_type_table.php
Labels: ♻️ Refactor

#184 Refactor: 行政関連seeder修正
  database/factories/MeetingRoomReservationFactory.php
  database/seeders/DatabaseSeeder.php
  database/seeders/MeetingRoomReservationSeeder.php
  database/seeders/MeetingRoomSeeder.php
  database/seeders/SalonBusinessHourSeeder.php
  database/seeders/SalonSeeder.php
  database/seeders/UserSeeder.php
Labels: ♻️ Refactor

#185 Docs: API文書を修正
  app/Http/Controllers/Admin/SalonServiceController.php
  app/Http/Controllers/User/UserController.php
  storage/api-docs/api-docs.json
Labels: 📝 Docs

#190 Migration: AS&Notice関連マイグレーションファイル修正
  app/Models/AfterServiceComment.php
  app/Models/Notice.php
  database/migrations/2014_10_12_000000_create_admins_table.php
  database/migrations/2024_01_18_071727_create_notices.php
  database/migrations/2024_01_18_081604_create_after_service_comments_table.php
Labels: 🐛 Fix

#191 Feat: notice関連機能を実装
  app/Http/Controllers/Admin/NoticeController.php
  app/Models/Notice.php
  app/Models/NoticeImage.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, 📝 Docs, 🐛 Fix

#192 Chore: scoutとtypesenseのsdkを追加
  app/Models/Notice.php
  composer.json
  composer.lock
  config/scout.php
Labels: 🔨 Chore

#195 Feat: noticeのfactoryとseederを実装
  database/factories/NoticeFactory.php
  database/seeders/DatabaseSeeder.php
  database/seeders/NoticeSeeder.php
Labels: ✨ Feat

#197 Refactor: 美容室サービス関連機能を改善
  app/Http/Controllers/Admin/SalonBreakTimeController.php
  app/Http/Controllers/Admin/SalonServiceController.php
  routes/api.php
Labels: ♻️ Refactor

#198 Refactor: ユーザー関連機能修正
  app/Http/Controllers/User/UserController.php
  app/Http/Controllers/User/UserSalonReservationController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ♻️ Refactor

#203 Fix: 美容室サービス関連エラーを修正
  app/Http/Controllers/Admin/SalonServiceController.php
Labels: 🐛 Fix

#204 Develop
  app/Http/Controllers/busTimeController.php
  app/Models/BusRoute.php
  app/Models/BusTime.php
  database/migrations/2024_02_21_212817_create_restaurant_weekend_meal_type_table.php
  database/migrations/2024_02_21_212823_create_restaurant_semester_meal_type_table.php
  database/migrations/2024_02_27_142546_create_bus_routes_table.php
  database/migrations/2024_02_27_150408_create_bus_times_table.php
Labels: ✨ Feat, 🐛 Fix

#205 bus_route 修正
  app/Http/Controllers/busTimeController.php
  app/Models/BusRoute.php
  database/migrations/2024_02_27_150408_create_bus_times_table.php
Labels: 🐛 Fix

#206 Chore: scoutとtypesenseのsdkを削除
  app/Http/Controllers/RestaurantSemesterController.php
  composer.json
  composer.lock
  config/scout.php
  storage/api-docs/api-docs.json
Labels: 🔨 Chore

#207 Chore: scoutとtypesenseのsdkを削除
  app/Models/Notice.php
Labels: 🔨 Chore

#208 Refactor: admin認証機能を改善
  app/Http/Controllers/Admin/AdminController.php
  app/Http/Controllers/User/UserController.php
  app/Http/Kernel.php
  app/Services/TokenService.php
  config/sanctum.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ♻️ Refactor, 📝 Docs

#209 feat: BusTimeController API 制作
  app/Http/Controllers/busTimeController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat

#211 Refactor: ログインレスポンスを変更
  app/Http/Controllers/Admin/AdminController.php
  app/Http/Controllers/User/UserController.php
  app/Models/User.php
Labels: ♻️ Refactor

#212 Feat: notice検索機能実装
  app/Http/Controllers/Admin/NoticeController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feat, 📝 Docs

#213 Fix: notice検索機能、adminパスワード確認機能を修正
  app/Http/Controllers/Admin/AdminController.php
  app/Http/Controllers/Admin/NoticeController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 📝 Docs, 🐛 Fix

#214 restaurant API 修正
  app/Http/Controllers/RestaurantMealTypeController.php
  app/Http/Controllers/RestaurantSemesterController.php
  app/Http/Controllers/RestaurantWeekendController.php
  app/Http/Controllers/SemesterMealTypeController.php
  app/Http/Controllers/WeekendMealTypeController.php
  app/Http/Controllers/busTimeController.php
  app/Models/RestaurantMealType.php
  app/Models/RestaurantMenu.php
  app/Models/RestaurantWeekend.php
  app/Models/RestaurantWeekendMealType.php
  app/Models/SemesterMealType.php
  app/Models/WeekendMealType.php
  database/migrations/2024_02_21_212448_create_semester_meal_type_table.php
  routes/api.php
Labels: 🐛 Fix

#215 api 修正
  docker-compose.yml
  routes/api.php
Labels: 🐛 Fix

#216 HOTFIX: docker-composeを修正
  app/Http/Controllers/Admin/NoticeController.php
  docker-compose.yml
Labels: 🚑 !HOTFIX

#217 weekendMealType swagger 修正
  app/Http/Controllers/WeekendMealTypeController.php
  storage/api-docs/api-docs.json
Labels: 🐛 Fix

#219 fix: docker 修正
  app/Http/Controllers/busScheduleController.php
  app/Http/Controllers/busTimeController.php
  app/Models/BusRoute.php
  app/Models/BusSchedule.php
  app/Models/BusTime.php
  database/migrations/2024_02_27_142546_create_bus_routes_table.php
  database/migrations/2024_02_27_150408_create_bus_times_table.php
  database/migrations/2024_02_28_192025_create_bus_schedules_table.php
Labels: 🐛 Fix

#220 Fix: notice作成機能を修正
  app/Http/Controllers/Admin/NoticeController.php
  app/Models/Admin.php
  app/Models/Notice.php
Labels: 🐛 Fix

#221 Fix: notice生成機能を修正
  app/Http/Controllers/Admin/NoticeController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ♻️ Refactor, 🐛 Fix

#228 Refactor: notice検索機能を改善
  app/Http/Controllers/Admin/NoticeController.php
  storage/api-docs/api-docs.json
Labels: ♻️ Refactor, 📝 Docs

#229 Feat: 認証関連のmiddlewareを実装
  app/Http/Controllers/User/UserController.php
  app/Http/Kernel.php
  app/Http/Middleware/ApproveCheck.php
  routes/api.php
Labels: ✨ Feat

#232 Chore: swaggerのstubを生成
  stubs/cast.inbound.stub
  stubs/cast.stub
  stubs/console.stub
  stubs/controller.api.stub
  stubs/controller.invokable.stub
  stubs/controller.model.api.stub
  stubs/controller.model.stub
  stubs/controller.nested.api.stub
  stubs/controller.nested.singleton.api.stub
  stubs/controller.nested.singleton.stub
  stubs/controller.nested.stub
  stubs/controller.plain.stub
  stubs/controller.singleton.api.stub
  stubs/controller.singleton.stub
  stubs/controller.stub
  stubs/controller.swagger.stub
  stubs/event.stub
  stubs/factory.stub
  stubs/job.queued.stub
  stubs/job.stub
  stubs/mail.stub
  stubs/markdown-mail.stub
  stubs/markdown-notification.stub
  stubs/middleware.stub
  stubs/migration.create.stub
  stubs/migration.stub
  stubs/migration.update.stub
  stubs/model.pivot.stub
  stubs/model.stub
  stubs/notification.stub
  stubs/observer.plain.stub
  stubs/observer.stub
  stubs/policy.plain.stub
  stubs/policy.stub
  stubs/provider.stub
  stubs/request.stub
  stubs/resource-collection.stub
  stubs/resource.stub
  stubs/rule.stub
  stubs/scope.stub
  stubs/seeder.stub
  stubs/test.stub
  stubs/test.unit.stub
  stubs/view-component.stub
Labels: 🔨 Chore

#234 fix: bus swagger 修正
  app/Http/Controllers/BusScheduleController.php
  storage/api-docs/api-docs.json
Labels: 🐛 Fix
